v1.0.0 (#20)
* feature: Adding more Lint and checks

* Adding new chain

* Normalize language names

* Add .Net unit test option

* Testing new chain of Jobs

* Fix Job dependency

* Fix Cypress job dependency

* Normalize SonarCloud names

* Drop plural of unit tests

* Change order on jobs names

* Sonar output (#10)

* Add: SonarCloud report reads from Action

* Add: Logic to pass if quality gate pass

* Add: Debug messages

* Feature: Changeable timeout (#8) (#11)

* add: Timeout for jobs as parameter
* add: Time out for Cypress job
* fix: Typo

* Simplify install packages scripts

* add: reactTest section

* fix: Job dependency

* fix: Jobs names

* fix: Jobs names

* Add conditionals to SonarCloud

* test: Passing down substantial changes

* fix: Substantial changes logic

* fix: Conditional logic

* Drop testing flags

* fix: .Net Sonar logic

* fix: Drop logic to avoid schedule tests fail

* fix: Cy-Runner run condition

* Fix pipeline for checkout-ui-custom (#14)

* Fix pipeline for checkout-ui-custom

* Fix typo in comment

* Fix other scripts to work with custom-ui (#17)

* Fix script on Cypress to fix checkot-ui error

* Add messages as non substantial changes (#19)

* Bump to match v1.0.0 (#18)

* feature: Adding more Lint and checks

* Adding new chain

* Normalize language names

* Add .Net unit test option

* Testing new chain of Jobs

* Fix Job dependency

* Fix Cypress job dependency

* Normalize SonarCloud names

* Drop plural of unit tests

* Change order on jobs names

* Sonar output (#10)

* Add: SonarCloud report reads from Action

* Add: Logic to pass if quality gate pass

* Add: Debug messages

* Feature: Changeable timeout (#8) (#11)

* add: Timeout for jobs as parameter
* add: Time out for Cypress job
* fix: Typo

* Simplify install packages scripts

* add: reactTest section

* fix: Job dependency

* fix: Jobs names

* fix: Jobs names

* Add conditionals to SonarCloud

* test: Passing down substantial changes

* fix: Substantial changes logic

* fix: Conditional logic

* Drop testing flags

* fix: .Net Sonar logic

* fix: Drop logic to avoid schedule tests fail

* fix: Cy-Runner run condition

* Fix pipeline for checkout-ui-custom (#14)

* Fix pipeline for checkout-ui-custom

* Fix typo in comment

* Fix other scripts to work with custom-ui (#17)

* Fix script on Cypress to fix checkot-ui error

* Add JSON lint check at bash level

* Fix check typo

* Fix missing var on JSON check

* Drop break link on JSON check script

* Add skip to avoid process message error

* Drop dummy lint tree test

* Add some debug code

* Change check logic

* Fix error output notation

* Add debug code

* Add var error on first check

* Check JSON files syntax on lint

* Add messages on ignore for Cypress

diff --git a/.github/workflows/quality-engineering.yml b/.github/workflows/quality-engineering.yml
--- a/.github/workflows/quality-engineering.yml
+++ b/.github/workflows/quality-engineering.yml
@@ -175,6 +175,7 @@ jobs:
           files_ignore: |
             CHANGELOG.md
             docs/**
+            messages/**
             .github/**
       - name: 'Do we have substantial changes?'
         run: echo ${{ steps.changed-files.outputs.any_modified }}
@@ -237,6 +238,28 @@ jobs:
         with:
           ref: ${{ github.event.pull_request.head.ref }}
           repository: ${{ github.event.pull_request.head.repo.full_name }}
+      - name: 'Lint JSON'
+        run: |
+          FAILED=0
+          for json in $(find -name "*.json" -not -path "*/node_modules/*"); do
+            ERROR=0
+            jq . -cM $json 1>/dev/null 2>error || ERROR=1
+            if [[ $ERROR -eq 0 ]]; then
+              echo "OK: $json"
+            else
+              FAILED=1
+              echo "ERROR: $json"
+              MSG=$(sed 's/\(.*\) at line \(.*\), column \(.*\)$/\1;\2;\3/' error)
+              F="$json"
+              E="$(echo $MSG | cut -d ';' -f1)"
+              L=$(echo $MSG | cut -d ';' -f2)
+              C=$(echo $MSG | cut -d ';' -f3)
+              echo "::error file=$F,line=$L,col=$C::$E"
+            fi
+          done
+          if [[ $FAILED -eq 1 ]]; then 
+            exit 1; 
+          fi
       - name: 'Set up Node.js'
         if: ( needs.safeCheck.outputs.substantialChanges == 'true' ) || ( github.event_name == 'push' )
         uses: actions/setup-node@v3
